version: '3'
services:
 app:
  build: './src'
  container_name: 'app'
  ports: 
   - '13334:13334'
  volumes: 
   - ./src:/server:Z
  command: uwsgi uwsgi.ini
  depends_on:
   - db
  expose:
    - 13334
 
 db:
  image: mysql:5.7
  container_name: 'db'
  ports:
   - "3306:3306"
  volumes:
   - ./mysql_data:/var/lib/mysql:Z
   - ./db:/dumpfile:Z
   - ./db/conf.d:/etc/mysql/conf.d:Z
  environment:
   MYSQL_ROOT_PASSWORD: root
   MYSQL_USER: test
   MYSQL_PASSWORD: test
   MYSQL_DATABASE: test1492_testtable

 nginx:
  build: ./nginx
  ports: 
   - 8080:80
  depends_on:
   - app

  





